### PR TITLE
fix: use a monotonic clock in memory storage

### PR DESCRIPTION
**Pull request by xrmx**
That should be more robust against system time update, e.g.
ntp or DST change.

### CODE REVIEW

**Comment by kgriffs** [comment]
This looks OK. monotonic() is a tiny bit slower than time(), but only by a few hundred ns, so nothing to worry about.

However, it is slow enough to slightly increase `ratio_of_negatives` in the `test_negative_count()` test. You will need to up the max used in the cert to get the test to pass again.

**Comment by xrmx** [comment]
Here it also fails in tests/test_multithreading.py:144: AssertionError
```
>       assert target_ratio < actual_ratio < ratio_max
E       assert 0.71 < 0.62
```

Not sure how to fix that

**Comment by vytas7** [comment]
Hi @xrmx !
And thanks for your great work maintaining uWSGI if I'm not mistaken :slightly_smiling_face: 

Just to clarify, even the normal `time.time()` is not subject to DST changes, and even small ntp updates can be sometimes applied in a monotonic fashion, depending on your OS and kernel version.

It seems [time.monotonic()](https://docs.python.org/3/library/time.html#time.monotonic) is now available in the standard lib since 3.5+, so we could probably use that where available.

**Comment by xrmx** [comment]
Hi @vytas7 

Python docs says it uses gettimeofday:

```
time() returns the most accurate time available (using Unix gettimeofday() where available)
```

gettimeofday man page says:

```
       The time returned by gettimeofday() is affected by discontinuous
       jumps in the system time (e.g., if the system administrator
       manually changes the system time).  If you need a monotonically
       increasing clock, see clock_gettime(2).
```

So the change still looks sensible to me, I've pushed using time.monotic() because it's clearer but CI still runs of Python 2 it'll not work. Said that I have no use for this PR so leave it for posterity :)

**Comment by vytas7** [comment]
Aha, right, good call regarding the underlying implementation... That does seem indeed susceptible to time adjustments. OTOH, DST doesn't, to my understanding, affect time.time().

I'll try to move this stuff to GH Actions, and drop 3.3 and 3.4 support.

Regarding 2.7, I guess we could also drop it since it's long past its EOL... OTOH it doesn't cost much to keep it unless a major development is planned, which seems less likely at this point.
@kgriffs thoughts?

**Comment by vytas7** [comment]
In contrast to the previously suggested 3rd party library, I'm not able to benchmark any meaningful performance difference between `time.time()` and `time.monotonic()` on modern CPythons.

So merging this :cowboy_hat_face:

**Review by vytas7 — APPROVED** [review]

**Comment by vytas7** [comment]
Released as part of https://github.com/falconry/token-bucket/releases/tag/0.3.0

**Pull request merged**
