### PR TITLE
chore: py312 compat; imp is gone, use importlib

### PR DESCRIPTION
**Pull request by supakeen**
The long-deprecated `imp` module is gone in Python 3.12. Use the `importlib` module to provide the same functionality.

Fedora is switching to Python 3.12 in rawhide (the upcoming Fedora 39 release). The `imp` module has been deprecated since Python 3.4 and is removed in 3.12.

This PR changes the `imp` usage to instead use `importlib`.

### CODE REVIEW

**Comment by supakeen** [comment]
If you wish I could add py311/py312 and remove py35 from/to your GH actions here as well or perhaps that should be a separate PR?

**Comment by CaselIT** [comment]
> If you wish I could add py311/py312 and remove py35 from/to your GH actions here as well or perhaps that should be a separate PR?

if you could it would be great!

**Comment by supakeen** [comment]
I've updated the CI to add `py311` and drop `py35` in this PR. It won't apply until it's on main I think (I'm not good at GitHub actions). I didn't add `py312` yet as it's still an alpha.

**Comment by supakeen** [comment]
I was wrong, it does apply them immediately here :)

**Comment by CaselIT** [comment]
> I've updated the CI to add `py311` and drop `py35` in this PR. It won't apply until it's on main I think (I'm not good at GitHub actions). I didn't add `py312` yet as it's still an alpha.

it's possible to add also 3.12 by setting the python version to `"3.12.0-alpha - 3.12"`

**Review by CaselIT — APPROVED** [review]

**Review by CaselIT — APPROVED** [review]

**Comment by CaselIT** [comment]
It probably makes sense to create a new release for this. cc @vytas7 @kgriffs

**Review by vytas7 — APPROVED** [review]
LGTM, thanks for this PR!
I've just taken the liberty of bumping up `python_requires` (this is actually much more important nowadays than Trove classifiers).

**Comment by CaselIT** [comment]
@vytas7 it probably makes sense to also release this to pypi.
can we fix also #23?

**Comment by vytas7** [comment]
Probably not yet re #23, I think it is better to tackle it incrementally, and I'd like to start with restructuring the project's architecture first along the lines of #10.

**Pull request merged**
